name: arch

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git git-lfs base-devel
          pacman -S --noconfirm hugo rsync openssh
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build project
        run: echo "Building project..."
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null /root/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /root/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> /root/.ssh/known_hosts

      - name: Check remote host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} hostnamectl
