name: I use Arch, btw
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git base-devel
          pacman -S --noconfirm hugo rsync openssh
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: |
          echo "Building project on Arch Linux"
          ls -la
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-build-artifact
          path: images/
          retention-days: 30
