name: I use Arch, btw
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Install packages
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git git-lfs base-devel
          pacman -S --noconfirm hugo rsync openssh
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Build project
        run: |
          echo "Building project on Arch Linux"
      - name: Setup SSH
        run: |
          echo "Setting up SSH for deployment"
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          cat ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_rsa -o "UserKnownHostsFile=~/.ssh/known_hosts" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} hostnamectl
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} hostnamectl
