name: ubuntu

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: "0.148.2"
      HUGO_ENVIRONMENT: "production"
      TZ: "Europe/Vienna"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
          sudo dpkg -i ${{ runner.temp }}/hugo.deb
      - name: Build project
        run: make build
      - name: Setup SSH
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Check remote host
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} hostnamectl
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hugo-site
          path: public/
